---
title: "GC Data Analysis"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Setup

```{r}
library(tidyverse)
library(lubridate)
source("source/theme_om23.R")
source("source/color_palettes.R")
```

```{r}
gc_data0 <- readRDS("cache/gc_samples0.RDS")
gc_data1 <- readRDS("cache/gc_samples1.RDS")
gc_data2 <- readRDS("cache/gc_samples2.RDS")

excluded <- readxl::read_excel("data/gc_data/excluded_gc_data.xlsx")
```

## Add difftime

#### Write an extract_date function

```{r}
extract_date <- function(input_string) {
  # Define the regular expression pattern to match the date format
  date_pattern <- "\\d{2}[A-Z]{3}\\d{2}"

  # Use str_extract to find the first occurrence of the pattern in the input string
  extracted_date <- str_extract(input_string, date_pattern)

  return(extracted_date)
}

# Test the function
input <- "data/gc_data/13MAR23FID_TC_16.RES"
result <- extract_date(input)
```

```{r}
gc_data <- bind_rows(gc_data0, gc_data1, gc_data2) |> 
  mutate(
    sampling_date = dmy(extract_date(file_name)),
    start_date = dmy("07FEB23"),
    dt = sampling_date - start_date
  )
```

## Add t0 data

```{r}
t0 <- tibble(
  well = c("BA3A", "BA4A", "BA1B")
) |> 
  crossing(
    depth = c(20, 150, 270),
    amendment = c("Bicarbonate", "Formate", "Acetate"),
    gas = c("CH4", "CO2")
  ) |> 
  mutate(
    depth = case_when(
      depth == 270 & well == "BA1B" ~ 250,
      TRUE ~ depth
    )
  ) |> 
  mutate(
    nmol_per_ml = 0,
    start_date = dmy("07FEB23"),
    sampling_date = dmy("07FEB23"),
    dt = sampling_date - start_date,
    peak_area = 0
    )

gc_data <- gc_data |> 
  bind_rows(t0) 

excluded_list <- excluded$excluded

gc_data_filtered <- gc_data |> 
  filter(!file_name %in% excluded_list)
```

# Plot

```{r}

gc_data_filtered |> 
  mutate(
    depth_str = factor(
      case_when(
        depth == 20 ~ "Shallow (20m)",
        depth == 150 ~ "Moderate (150m)",
        depth == 250 ~ "Deep (250/270m)",
        depth == 270 ~ "Deep (250/270m)"
      ),
    levels = c("Shallow (20m)", "Moderate (150m)", "Deep (250/270m)")
    )
    ) |> 
  mutate(well = factor(well, levels = c("BA1B", "BA4A", "BA3A"))) |> 
  filter(gas == "CH4") |> 
  ggplot(
    aes(x = dt,
        y = peak_area,
        color = amendment,
        shape = amendment,
        linetype = amendment,
        label = file_name
        )
  ) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  facet_grid(depth_str~well) +
  scale_color_manual(values = amendment_palette) +
  ggprism::annotation_ticks(sides = "trbl") +
  theme_bw() +
  labs(
    x = "Incubation time (days)",
    #y = latex2exp::TeX("nmol $CH_4$ $ml^{-1}$")
  ) +
  theme_om23() +
  theme(
    panel.grid = element_blank(),
    aspect.ratio = 1
  )
#plotly::ggplotly()
```

```{r}
gc_data_filtered |> 
  filter(gas == "CH4") |> 
  ggplot(
    aes(x = dt,
        y = peak_area,
        color = amendment,
        shape = amendment,
        linetype = amendment,
        label = file_name
        )
  ) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(well, depth)) +
  scale_color_manual(values = amendment_palette) +
  #scale_x_continuous(breaks = c(0, 30, 60, 120, 180)) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#e3e3e3", color = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    strip.background.x = element_rect(fill = "black"),
    strip.text = element_text(color = "white"),
    panel.border = element_rect(linewidth = 1.2, color = "black"),
    axis.ticks.x = element_blank(),
    #legend.position = "None"
    )
```
