---
title: "Cline Data Vizualization"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Setup

```{r}
rm(list=ls()) # Clear the environment
library(tidyverse)
library(ggrepel)
```

### Read from cache

```{r}
df1 <- read_rds("cache/2023-05-23-cline_data.RDS")
df2 <- read_rds("cache/2023-06-05-cline_data.RDS")

# combine the two datasets
clines <- bind_rows(df1, df2) |> 
  mutate(dt = case_when(
    sample_set == "CTL" ~ 0,
    sample_set == "B" ~ 118,
    sample_set == "A" ~ 34,
  ))

# pull the controls
clines_ctls <- clines |> filter(amendment == "Control") |> 
  #rename(CTL.conc.um = conc.um) |> 
  select(conc.um, sd.conc.um, well, depth) |> 
  crossing(amendment = c("Acetate", "Formate", "Bicarbonate")) |> 
  mutate(sample_set = "CTL",
         dt = 0)

clines_wctls <- clines |> 
  filter(amendment != "Control") |> 
  bind_rows(clines_ctls)
  
rm(df1, df2) # remove excess tibbles
```

# Plot

```{r}
source("source/color_palettes.R")

p_clines <- clines_wctls |> 
  mutate(depth_str = case_when(
    depth == 20 ~ "Shallow (20m)",
    depth == 150 ~ "Intermediate (150m)",
    depth == 250 ~ "Deep (250/270m)",
    depth == 270 ~ "Deep (250/270m)"
  )) |> 
  mutate(depth_str = fct_rev(depth_str)) |> 
  ggplot(
    aes(x = dt,
        y = conc.um,
        color = amendment,
        linetype = amendment,
        shape = amendment)
  ) +
  geom_point() +
  scale_color_brewer(palette = "Set1") +
  geom_line() +
  geom_errorbar(aes(
    ymin = conc.um - sd.conc.um,
    ymax = conc.um + sd.conc.um
    ),
    width = 3,
    linetype = "solid"
  ) +
  facet_grid(well~depth_str) +
  theme_bw() +
  labs(
    x = "Incubation Time (Days)",
    y = "Total Sulfide (µM)",
    color = "Carbon Source",
    shape = "Carbon Source",
    linetype = "Carbon Source"
  ) +
  theme(
    panel.grid.minor = element_blank(),
    axis.text = element_text(color = "black"),
    strip.background = element_blank()
  )
p_clines
```

```{r}
cowplot::save_plot(
  filename = "fig_output/cline_assays.pdf",
  plot = p_clines,
  base_height = 6, base_width = 7
)
```
