Templeton
Templeton
N2024


03/13/2023 14:07:18
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
13MAR23FID_TC_15.CHR
BA1B-20-AC-A-0.5ml
TC


"CH4",3.104,1357.6753,198.042,0.0492,""
