Templeton
Templeton
N2024


09/29/2023 12:21:06
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
29SEP23_TAC_FID_06.CHR
BA3A-20-FORM-A-0.5ml
TC


"CH4",3.190,5484.4151,676.963,0.1987,""
