Templeton
Templeton
N2024


06/01/2023 11:29:45
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
01JUN23_TAC_FID_14.CHR
BA4A-20-BIC-0.5ml-T2
TC


"CH4",3.068,1713.0924,233.512,0.0621,""
