Templeton
Templeton
N2024


06/01/2023 14:26:42
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
01JUN23_TAC_FID_33.CHR
BA1B-20-BIC-0.5ml-BT2
TC


"CH4",3.104,12255.1116,1462.490,0.4440,""
