Templeton
Templeton
N2024


06/01/2023 15:45:13
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
01JUN23_TAC_FID_46.CHR
BA4A-150-FORM-0.5ml-BT2
TC


"CH4",3.097,2575.3552,300.604,0.0933,""
