Templeton
Templeton
N2024


03/13/2023 17:27:06
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
03MAR23FID_TC_45.CHR
BA3A-150-Bic-A-0.5ml
TC


"CH4",3.090,10.1982,1.404,0.0004,""
