Templeton
Templeton
N2024


03/13/2023 15:19:59
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
13MAR23FID_TC_28.CHR
BA4A-150-Form-A-0.5ml
TC


"CH4",3.076,1291.5387,150.987,0.0468,""
