Templeton
Templeton
N2024


08/11/2023 11:06:06
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
11AUG23_TAC_FID_08.CHR
BA3A-20-Bic-B-0.5ml
TC


"CH4",3.206,3891.9205,492.218,0.1410,""
